//
//  UserRegister.swift
//  QobuzKit
//
//  Created by Markus Rosenhave on 23/02/2025.
//

import Foundation

extension QobuzAPI.Endpoints {
  /**
   Create an Qobuz account. Return a session token for a user.
   
   - Parameter username: The username
   - Parameter email: The email
   - Parameter password: The users password (This is encrypted automatically before sending request)
   - Parameter birthdate: The users birthdate
   - Parameter gender: The users gender
   - Parameter partnersOptin: I don't know what this does
   - Parameter deviceManufacturerId: ID generated by the client's application with data from the device
   
   ## Authentication
   Requires a valid app_id.
   
   
   - Returns: A QBUserLogin object. Includes the **user auth token**.
  */
  public struct UserRegister: Endpoint {
    public init(
      username: String,
      email: String,
      password: String,
      birthdate: Date,
      gender: UserRegisterGender,
      partnersOptin: Bool? = nil,
      deviceManufacturerId: String? = nil
    ) {
      let formatter = DateFormatter()
      formatter.dateFormat = "dd/MM/yyyy"
      self.parameters = [
        .init(name: QobuzAPI.Parameters.username(), value: username),
        .init(name: QobuzAPI.Parameters.email(), value: email),
        .init(name: QobuzAPI.Parameters.birthdate(), value: formatter.string(from: birthdate)),
        .init(name: QobuzAPI.Parameters.gender(), value: gender.rawValue)
      ]
      let hashedPassword = self.calculateMD5Hash(for: password)
      self.parameters.append(.init(name: QobuzAPI.Parameters.password(), value: hashedPassword))
      
      if let partnersOptin {
        self.parameters.append(.init(name: QobuzAPI.Parameters.partnersOptin(), value: String(partnersOptin)))
      }
      
      if let deviceManufacturerId {
        self.parameters.append(.init(name: QobuzAPI.Parameters.deviceManufacturerId(), value: deviceManufacturerId))
      }
      
    }

    public typealias Response = QBUserLogin

    public let path: String = "user/register"

    public var parameters: [URLQueryItem]
    
    public enum UserRegisterGender: String {
      case male
      case female
      case other
    }
  }
}
